version: '3.9'
services:
  client:
    container_name: client-delivery
    working_dir: /front-end
    volumes: 
      - ./front-end/src:/front-end/src
    restart: always
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    networks:
      - app-net
  api:
    container_name: api-delivery
    working_dir: /back-end
    volumes: 
      - ./back-end/src:/back-end/src
    restart: always
    command: dev
    build: ./back-end
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - MYSQL_PORT=3306
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - API_PORT=3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    networks:
      - app-net
  db:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: db-delivery
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    networks:
      - app-net

networks:
  app-net:

